stages:
  - build-web
  - build-windows
  - build-linux

build-web:
  artifacts:
    name: "$CI_COMMIT_REF_NAME"
    paths:
      - generated/web
  variables:
    BUILD_TARGET: "web"
    GIT_STRATEGY: clone
  tags:
    - web
  stage: build-web
  script:
    - ./install.sh
  
build-windows:
  artifacts:
    name: "$CI_COMMIT_REF_NAME"
    paths:
      - generated/windows
  variables:
    BUILD_TARGET: "windows"
    GIT_STRATEGY: clone
  tags:
    - windows
  stage: build-windows
  script:
    - ./install.sh

build-linux:
  artifacts:
    name: "$CI_COMMIT_REF_NAME"
    paths:
      - generated/linux
  variables:
    BUILD_TARGET: "linux"
    GIT_STRATEGY: clone
  tags:
    - linux
  stage: build-linux
  script:
    - ./install.sh